### ISSUE TITLE
关于tabbar 的问题

### ISSUE THREAD

**Issue by wangchaodong** [ZhongTaoTian/SmallDay#1]
请问你的这个self.setValue(MainTabBar(), forKey: "tabBar") 的作用是什么?

**Comment by ZhongTaoTian** [comment]
通过kvc将UITabBarController.tabBar替换成自定义的tabBar

**Comment by wangchaodong** [comment]
我一开始仿照你的tabbar+navigationbar写demo, 我运行的时候tabbar不见了.      

```
let nv = MainNavigationController(rootViewController: vc)  //继承自uinavigationcontrollerr的mainNC 运行时tabbar没了....
let nv = UINavigationController(rootViewController: vc) //改成默认的UInavigationCtroller tabbar正常显示   
```

   然后, 我在你的代码里面把这个self.setValue(MainTabBar(), forKey: "tabBar") 注释了之后, SmallDay 的tabbar正常显示....(已经凌乱了,希望能得到解答)

**Comment by wangchaodong** [comment]
我发现问题所在了, 我在mainviewcontroller里面没有进行self.childViewControllers.count>0的判断,然后进入tabbar的页面时,就直接隐藏了(貌似是这样,不太确定,不过问题解决了) 多谢小熊 
- 这个项目代码很多学习的地方.

**Comment by ZhongTaoTian** [comment]
我将这个每次推新控制器，隐藏地步的tabbar的操作封装到了自定义的UINavigationController里面了，在PUSH的时候做相应的判断

**Comment by wangchaodong** [comment]
thx, 我看你代码时注意到这个, 没注意到对子视图数量判断...  
不过

```
self.setValue(MainTabBar(), forKey: "tabBar") 
```

这个视乎有没有都不会影响结果.

**Comment by HYLoginCoder** [comment]
嗯，主要是还个背景图，主要是背景图也是白色的，所以没啥效果。。。

在 2015-10-27 09:50:32，wangchaodong notifications@github.com 写道：

thx, 我看你代码时注意到这个, 没注意到对子视图数量判断...

不过

self.setValue(MainTabBar(), forKey: "tabBar") 

这个视乎有没有都不会影响结果.
