### ISSUE TITLE
关于业务模型!

### ISSUE THREAD

**Issue by wangchaodong** [ZhongTaoTian/SmallDay#2]
小熊能不能有空在博客里把业务模型的思路给我们这些初学者讲解下!... 只是看代码的话,我还是不能完全理解.

**Comment by ZhongTaoTian** [comment]
恩,最近实在忙,博客啥的都没更新..等忙完这段日子的吧 估计的2个月左右

**Comment by wangchaodong** [comment]
好的,小熊.
